name: Deploy Static Site to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: https://familykebabhousestalham.github.io/FAMILYKEBABHOUSE/

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build client & server
        run: npm run build

      - name: Prepare docs folder
        run: npm run prepare-docs

      - name: Enable & Configure Pages
        uses: actions/configure-pages@v5
        with:
          enablement: all

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs

      - name: Deploy to GitHub Pages
        id: deploy_pages
        uses: actions/deploy-pages@v4
