name: Build & Deploy Static Site

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: https://familykebabhousestalham.github.io/FAMILYKEBABHOUSE/

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build client & server
        run: npm run build

      - name: Prepare docs folder
        run: npm run prepare-docs

      - name: Enable & configure Pages
        uses: actions/configure-pages@v5
        with:
          enablement: all

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs

      - name: Deploy to GitHub Pages
        id: deploy_pages
        uses: actions/deploy-pages@v4
